Final.pdf: Final.tex Final.bib
		pdflatex Final.tex
		bibtex Final
		pdflatex Final.tex
		pdflatex Final.tex
clean:	
		rm -f Final.pdf *.aux *.blg *.bbl *.log *.tmp *.xref *.idv *.4og *.4ct *.lg *.4tc *~
